version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: noticeboard-mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass!@#$
      MYSQL_DATABASE: noticeboard
      MYSQL_USER: admin
      MYSQL_PASSWORD: pass!@#$
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: